<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tickets</name>
   <tag></tag>
   <elementGuidId>0056b0d8-6000-42fb-94b4-5eef058e49b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tickets']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tickets</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf4bd258-f1cf-4ac8-a046-d42898356ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tickets</value>
      <webElementGuid>989af988-9057-4f54-882c-3449d3bfe7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button primary</value>
      <webElementGuid>8241e2c5-9b04-4f71-9c56-0950e10cc13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tickets</value>
      <webElementGuid>bebf19dd-ccfc-4c11-8798-287e67dfebf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tickets&quot;)</value>
      <webElementGuid>a54ae3d4-db07-47be-8ca9-53009a652a1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='tickets']</value>
      <webElementGuid>febb1c12-9749-4c60-a726-e3a6bf97a96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ng-component[@id='container']/div/button)[2]</value>
      <webElementGuid>befb5518-cebb-4407-8dbe-98132ee6bf3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lamp Failure Report'])[1]/following::button[6]</value>
      <webElementGuid>4a3d9292-3146-4395-adb4-701b58f9d2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OpenStreetMap'])[1]/following::button[12]</value>
      <webElementGuid>0e96c0ed-9219-412a-bffe-9ec33a528f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CCMS Panel View'])[1]/preceding::button[1]</value>
      <webElementGuid>6bc3ecbc-cda9-4a32-a4ba-df3100cd83a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UID'])[1]/preceding::button[10]</value>
      <webElementGuid>290cdb21-23cd-49e8-8d54-a281af1c758b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tickets']/parent::*</value>
      <webElementGuid>665318aa-d3bd-4b1d-88c4-d8faca3859e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//gridster-item[9]/tb-widget-container/div/div[2]/tb-widget/div/div/ng-component/div/button</value>
      <webElementGuid>a9ac5442-dd5c-4ffa-85b9-083c9371b536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'tickets' and (text() = 'Tickets' or . = 'Tickets')]</value>
      <webElementGuid>29ffbd4f-f186-4b73-bc96-9593226b66c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
