<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Complainer Phone Number</name>
   <tag></tag>
   <elementGuidId>82e430be-b1e0-4efa-ba55-e1828f5da681</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']/ng-component/form/div[2]/div[6]/mat-form-field[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c175-328</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8fe5caf7-9a52-4bb4-9402-adff266469bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix ng-tns-c175-328</value>
      <webElementGuid>108d73ef-cc37-4009-a2c4-efb7a9ab84fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Complainer Phone Number</value>
      <webElementGuid>90c25be0-9e95-42fc-8cf3-98aba5fe38d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/ng-component[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;mat-dialog-content&quot;]/div[6]/mat-form-field[@class=&quot;mat-form-field mat-block ng-tns-c175-328 mat-primary ng-star-inserted mat-form-field-type-mat-input mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c175-328&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c175-328&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c175-328&quot;]</value>
      <webElementGuid>630d0ae5-aaef-4b30-9dd7-f10164541324</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/ng-component/form/div[2]/div[6]/mat-form-field[2]/div/div/div</value>
      <webElementGuid>329796ab-78a9-434b-8819-6cd40880807d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complainer'])[1]/following::div[7]</value>
      <webElementGuid>26a0aa95-d14a-44ff-8533-068b2ab79f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Officials'])[1]/following::div[9]</value>
      <webElementGuid>7b001e07-2d43-4e69-8a7e-2b48cfc0147a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created By'])[1]/preceding::div[5]</value>
      <webElementGuid>b8ff7831-7164-4c94-a2a0-bcef3482a02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/mat-form-field[2]/div/div/div</value>
      <webElementGuid>7c9eba42-ac67-4fbf-be4e-7ea9594b7db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Complainer Phone Number' or . = 'Complainer Phone Number')]</value>
      <webElementGuid>823639ea-25be-4127-b66d-6ff1b00c71ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
