<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Salem</name>
   <tag></tag>
   <elementGuidId>d4be044e-852c-44f8-a69c-a87f48e9e081</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='mat-input-31']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-input-31</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d9e33088-4727-47cc-a23d-275d0fff1436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c175-237 cdk-text-field-autofill-monitored</value>
      <webElementGuid>c9233a15-9814-42d0-82eb-6ed8329b8136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-31</value>
      <webElementGuid>32facdde-77fc-4f6b-9d58-39a2542991c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8e126b87-a35a-4c69-912f-316c52415f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fdfca8ed-b6c9-4b8e-9b45-ae768d97be7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salem</value>
      <webElementGuid>4c73da68-3641-47c7-a6b8-ba00226292ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-31&quot;)</value>
      <webElementGuid>1dd2a22c-2e08-4c79-a986-4edb69517299</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='mat-input-31']</value>
      <webElementGuid>e53e2709-3925-4350-8859-9d36361c236d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/ng-component/form/div[2]/div/mat-form-field[2]/div/div/div/select</value>
      <webElementGuid>f150ca70-b6bd-4299-8509-89a6061594d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[2]/following::select[1]</value>
      <webElementGuid>fc5bf673-9715-4b33-b88f-0d6ffedbaa1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SmartLights-Ticketing system'])[1]/following::select[2]</value>
      <webElementGuid>53bff2f8-308b-4fbc-89cc-1c184afe6130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project'])[2]/preceding::select[1]</value>
      <webElementGuid>c4255896-2561-4919-a532-1b65e5b7db3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity Type'])[1]/preceding::select[1]</value>
      <webElementGuid>6395e829-4f7b-4612-b115-e26539fc6d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[2]/div/div/div/select</value>
      <webElementGuid>574d2bac-3475-4741-af9f-ba0a5f74afa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'mat-input-31' and (text() = 'Salem' or . = 'Salem')]</value>
      <webElementGuid>9c2e577e-ab43-43fd-8406-435f82c5d5d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
