<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Day time burning</name>
   <tag></tag>
   <elementGuidId>6ccf1c39-bde3-40d8-b2ab-0ffd95da1042</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-126']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-126 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>82da596b-342f-4578-89ec-e024e0d72deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>b6665364-b0bb-4c97-be29-151c22c533df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Day time burning </value>
      <webElementGuid>4d31f0c0-e3fd-43e6-a630-367af2a42b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-126&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>a907472d-3258-424c-a759-06e2445c08ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-126']/span</value>
      <webElementGuid>234f7796-6dfe-4671-9d99-b02a516ee332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flickering'])[2]/following::span[1]</value>
      <webElementGuid>792efeb2-5863-4c36-af55-212fd2d2e446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not burning'])[1]/following::span[2]</value>
      <webElementGuid>d9cb81e4-0406-4b7d-9fbd-2419802113ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lamps not burning'])[1]/preceding::span[1]</value>
      <webElementGuid>8bacb0bd-2e9f-4d24-9624-33bae679817e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timing issue'])[1]/preceding::span[2]</value>
      <webElementGuid>183b4137-0353-491b-9d54-a634af6d71c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Day time burning']/parent::*</value>
      <webElementGuid>a3be8f53-a8df-4003-b850-0ac2746e2ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[3]/span</value>
      <webElementGuid>07e7d34a-1b9f-49cc-a14c-6460f08e5922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Day time burning ' or . = 'Day time burning ')]</value>
      <webElementGuid>949ea9b5-2b72-4e1e-b7e3-4979345c752d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
