<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Lamps not burning</name>
   <tag></tag>
   <elementGuidId>d9219f46-0bbc-4e10-9a03-325c065abe4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-204']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-204 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9b8e109b-349c-411f-9821-b7a68ddef7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>ebcead05-796f-40ea-b883-83cab2e659a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lamps not burning </value>
      <webElementGuid>73779024-896c-488d-8caa-8a714b6e6a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-204&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>35ece1cd-a8dd-4b2d-9cda-74f10e4671cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-204']/span</value>
      <webElementGuid>9f5d3f35-8594-44e2-a4ae-7ef4633131bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day time burning'])[1]/following::span[1]</value>
      <webElementGuid>92e8e247-9e67-4083-8b74-ec82b2e1a29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flickering'])[2]/following::span[2]</value>
      <webElementGuid>7012cda0-356f-451e-8919-2e016a942304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Timing issue'])[1]/preceding::span[1]</value>
      <webElementGuid>dbf08549-ab63-4e7e-9b30-0f9b8aebbc6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MCB trip'])[1]/preceding::span[2]</value>
      <webElementGuid>9e6d9f60-5d48-425b-85c0-b23bf1824a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lamps not burning']/parent::*</value>
      <webElementGuid>f9c3dd7a-dfd8-44f6-a2e5-45e575896c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[4]/span</value>
      <webElementGuid>0230eab0-5f5f-4f43-84b6-6c0b7c8f6b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Lamps not burning ' or . = 'Lamps not burning ')]</value>
      <webElementGuid>acec92c3-43b8-499e-be77-ea16e7da4030</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
