<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Councillor</name>
   <tag></tag>
   <elementGuidId>55bcd362-5cc7-49ea-bf99-072f74bd69b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-151']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-151 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cdfb20a9-c867-481f-932a-6efe1b3ab533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>658bd09f-eb96-4048-bd48-44a9faf90b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Councillor </value>
      <webElementGuid>164bece8-9121-4beb-90d8-08428b0166da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-151&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>680c9e2a-5735-414c-922d-bad0d15d049d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-151']/span</value>
      <webElementGuid>ef31669f-5f44-4229-848a-a57f3c4542d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[2]/following::span[1]</value>
      <webElementGuid>9d22cdd9-ba4c-45c1-9413-5b5f903af423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O&amp;M (CMS)'])[1]/following::span[2]</value>
      <webElementGuid>2d9909dd-b443-44fa-b651-4bbed4da52b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Officials'])[1]/preceding::span[1]</value>
      <webElementGuid>5defcda9-66dc-44f7-bcf3-5b780fb7493c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='V-Team'])[1]/preceding::span[2]</value>
      <webElementGuid>eeedc81d-881b-43fa-8ce0-a312aed2e123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Councillor']/parent::*</value>
      <webElementGuid>7a82e237-68f1-4d57-852d-dcf3824d0780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[3]/span</value>
      <webElementGuid>acc8b50b-269f-4fa2-bda3-dc063aa3c535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Councillor ' or . = 'Councillor ')]</value>
      <webElementGuid>61c75b7a-3f01-4848-87fe-5362868341e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
