<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Timing issue</name>
   <tag></tag>
   <elementGuidId>a417be54-fcaa-4352-9b18-b7c6df063665</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-128']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-128 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e3d64403-54c3-4ba3-b5cf-284828de20de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>d807c3c7-4559-4f3c-817b-8affc3ab6d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Timing issue </value>
      <webElementGuid>565baa4d-e9e5-4e75-982c-38b26a38c6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-128&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>1501a70d-a532-4bef-b1bd-bb116fd6e09f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-128']/span</value>
      <webElementGuid>b82964be-f326-4f41-836d-78d0379532ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lamps not burning'])[1]/following::span[1]</value>
      <webElementGuid>d395b4d0-20bf-4b2a-a02c-df7506a82536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day time burning'])[1]/following::span[2]</value>
      <webElementGuid>d2247ac9-e306-4c5a-9ed4-4923718c1e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MCB trip'])[2]/preceding::span[1]</value>
      <webElementGuid>2ad4f826-e1d5-4d62-881a-2a9da33e5b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='High Voltage'])[1]/preceding::span[2]</value>
      <webElementGuid>46d46a34-87a4-4b5b-8ff6-957843e28cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Timing issue']/parent::*</value>
      <webElementGuid>b72b103c-3b38-43f5-9194-c9ef34a52cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[5]/span</value>
      <webElementGuid>7a250777-7e1a-4518-982e-39f2a6bdac75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Timing issue ' or . = 'Timing issue ')]</value>
      <webElementGuid>dd0d65aa-efe3-405f-95a7-b20e39af6eaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
